import pyautogui as p

while True:
    p.sleep(3)
    print("Iniciando o bomb")
    pesquisar = p.locateCenterOnScreen("barra cima.png")
    p.moveTo(pesquisar, duration=1)
    p.click()
    p.sleep(3)
    p.write("https://app.bombcrypto.io/")
    p.press('enter')
    p.sleep(5)
    atualizar = p.locateCenterOnScreen("atualizar.png")
    print("atualizando pagina")
    p.moveTo(atualizar, duration=1)
    p.click()
    p.sleep(10)
    entrar = p.locateCenterOnScreen("connect-wallet.png")
    print('Conectando a carteira')
    p.moveTo(entrar, duration=1)
    p.sleep(5)
    p.click()
    p.sleep(5)
    assinar = p.locateCenterOnScreen("Assinar.png")
    p.moveTo(assinar, duration=1)
    p.click()
    p.sleep(15)
    heroes = p.locateCenterOnScreen("hero.png")
    print('Procurando heros')
    p.moveTo(heroes, duration=1)
    p.click()
    p.sleep(8)
    trab = p.locateCenterOnScreen("trab.png")
    print('Botando todos para trabalhar')
    p.moveTo(trab, duration=1)
    p.click()
    p.sleep(5)
    print('Fechando tela de trabalho')
    fechar = p.locateCenterOnScreen("close.png")
    p.moveTo(fechar, duration=1)
    p.click()
    p.sleep(5)
    print('Indo para tela de mineração')
    trab = p.locateCenterOnScreen("trb.png")
    p.moveTo(trab, duration=1)
    p.click()
    print('Esperando 10 minutos para reiniciar')
    p.sleep(600)
